version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.17.0
    environment:
      - xpack.security.enabled=false  # Disable to use Elasticsearch’s authentication, authorization and audit features
      - discovery.type=single-node  # Switch default mode from multi-node to single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.17.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
